import { AbsolutePosition } from "../boilerplate";
import { ORDER_PUNJAB_1, ORDER_DELHI_1, ORDER_DELHI_2, ORDER_DELHI_3, ORDER_BENGAL_1, ORDER_BENGAL_2, ORDER_BOMBAY_1, ORDER_BOMBAY_2, ORDER_BOMBAY_3, ORDER_MARATHA_1, ORDER_MARATHA_2, ORDER_MARATHA_3, ORDER_HYDERABAD_1, ORDER_MYSORE_1, ORDER_MYSORE_2, ORDER_MADRAS_1, ORDER_MADRAS_2, SETUP, LONDON_SEASON, FAMILY, FIRMS, HIRING, CHAIRMAN, DIRECTOR_OF_TRADE, MANAGER_OF_SHIPPING, MILITARY_AFFAIRS, BOMBAY_PRESIDENCY, MADRAS_PRESIDENCY, BENGAL_PRESIDENCY, SUPERINTENDENT_OF_TRADE_IN_CHINA, BONUSES, REVENUE, EVENTS_IN_INDIA, PARLIAMENT_MEETS, UPKEEP_AND_REFRESH, BOMBAY_ARMY, BENGAL_ARMY, MADRAS_ARMY, BOMBAY_WRITERS, BENGAL_WRITERS, MADRAS_WRITERS, STOCK_EXCHANGE_2, STOCK_EXCHANGE_3_LEFT, STOCK_EXCHANGE_3_RIGHT, STOCK_EXCHANGE_4, STOCK_EXCHANGE_5, WEST_INDIAN, SOUTH_INDIAN, EAST_INDIAN, PRESIDENT_OF_BOMBAY, PRESIDENT_OF_MADRAS, PRESIDENT_OF_BENGAL, GOVERNOR_GENERAL, GOVERNOR_OF_BOMBAY, GOVERNOR_OF_MADRAS, GOVERNOR_OF_BENGAL, GOVERNOR_OF_PUNJAB, GOVERNOR_OF_DELHI, GOVERNOR_OF_MARATHA, GOVERNOR_OF_HYDERABAD, GOVERNOR_OF_MYSORE, BENGAL, BOMBAY, DELHI, HYDERABAD, MADRAS, MARATHA, MYSORE, PUNJAB } from "../constants";

// Array with top, left coords for each order
export const ORDERS_CONFIG: Record<string, AbsolutePosition> = {
  [ORDER_PUNJAB_1]: { top: 40, left: 212 },
  [ORDER_DELHI_1]: { top: 28, left: 425 },
  [ORDER_DELHI_2]: { top: 79, left: 565 },
  [ORDER_DELHI_3]: { top: 102, left: 377 },
  [ORDER_BENGAL_1]: { top: 182, left: 749 },
  [ORDER_BENGAL_2]: { top: 273, left: 902 },
  [ORDER_BOMBAY_1]: { top: 145, left: 246 },
  [ORDER_BOMBAY_2]: { top: 275, left: 312 },
  [ORDER_BOMBAY_3]: { top: 370, left: 225 },
  [ORDER_MARATHA_1]: { top: 176, left: 584 },
  [ORDER_MARATHA_2]: { top: 281, left: 431 },
  [ORDER_MARATHA_3]: { top: 348, left: 665 },
  [ORDER_HYDERABAD_1]: { top: 476, left: 526 },
  [ORDER_MYSORE_1]: { top: 544, left: 345 },
  [ORDER_MYSORE_2]: { top: 632, left: 403 },
  [ORDER_MADRAS_1]: { top: 629, left: 550 },
  [ORDER_MADRAS_2]: { top: 706, left: 502 },
};